# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Akbar Arif
"""Keep every embedded diagram identical to its single source file.

Sources live in diagrams/src/*.mmd. Articles embed a diagram between markers:

    <!-- diagram:start d01-request-lifecycle -->
    ...anything, replaced on sync...
    <!-- diagram:end -->

Usage:
    python tools/sync_diagrams.py          rewrite embeds and diagrams/README.md
    python tools/sync_diagrams.py --check  exit 1 if anything is out of date (CI)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "diagrams" / "src"
EXPORT = ROOT / "diagrams" / "export"
MARKED = re.compile(r"<!-- diagram:start (\S+) -->.*?<!-- diagram:end -->", re.S)
FENCE = "`" * 3


def embed(name: str) -> str:
    body = (SRC / f"{name}.mmd").read_text(encoding="utf-8").rstrip("\n")
    return f"<!-- diagram:start {name} -->\n{FENCE}mermaid\n{body}\n{FENCE}\n<!-- diagram:end -->"


def title_of(path: Path) -> str:
    first = path.read_text(encoding="utf-8").splitlines()[0]
    m = re.match(r"%% title: (.+)", first)
    return m.group(1) if m else path.stem


def gallery() -> str:
    items: list[tuple[str, str]] = []
    for p in sorted(SRC.glob("*.mmd")):
        items.append((p.stem, f"## {p.stem[:3].upper()}: {title_of(p)}\n\n{embed(p.stem)}\n"))
    for p in sorted(EXPORT.glob("*.svg")):
        name = p.stem[4:].replace("-", " ").capitalize()
        items.append((p.stem, f"## {p.stem[:3].upper()}: {name}\n\n![{name}](export/{p.name})\n"))
    items.sort(key=lambda kv: kv[0])
    head = (
        "# Diagram gallery\n\n"
        "Generated by `tools/sync_diagrams.py`; do not edit by hand. Edit the sources in\n"
        "`src/` (Mermaid) and rerun the script. `D04` is drawn by `tools/roofline_svg.py`\n"
        "from the hardware specs in `src/ie/hardware.py`.\n\n"
    )
    return head + "\n".join(body for _, body in items)


def targets() -> list[Path]:
    files = [ROOT / "README.md", *sorted((ROOT / "curriculum").glob("*.md"))]
    return [f for f in files if f.exists()]


def main() -> int:
    check = "--check" in sys.argv
    stale: list[str] = []

    def write(path: Path, new: str) -> None:
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != new:
            stale.append(str(path.relative_to(ROOT)))
            if not check:
                path.write_text(new, encoding="utf-8", newline="\n")

    for f in targets():
        text = f.read_text(encoding="utf-8")
        write(f, MARKED.sub(lambda m: embed(m.group(1)), text))
    write(ROOT / "diagrams" / "README.md", gallery())

    if stale:
        verb = "out of date" if check else "updated"
        print(f"{verb}: " + ", ".join(stale))
    return 1 if (check and stale) else 0


if __name__ == "__main__":
    sys.exit(main())
